project_name: kube-shutdown-after
release:
  github:
    owner: caarlos0
    name: kube-shutdown-after
builds:
  - goos:
      - linux
    goarch:
      - amd64
    binary: kube-shutdown-after
    env:
      - CGO_ENABLED=0
archives:
  - id: kube-shutdown-after
    name_template: "{{ .Binary }}_{{ .Os }}_{{ .Arch }}"
    files:
      - LICENSE*
      - README*
    format: tar.gz
dockers:
  - image_templates:
      - "caarlos0/kube-shutdown-after:{{ .Tag }}"
      - "caarlos0/kube-shutdown-after:v{{ .Major }}.{{ .Minor }}"
      - "caarlos0/kube-shutdown-after:latest"
