project_name: kube-shutdown-after
release:
  github:
    owner: caarlos0
    name: kube-shutdown-after
builds:
- goos:
  - linux
  goarch:
  - amd64
  binary: kube-shutdown-after
  env:
  - CGO_ENABLED=0
archive:
  format: tar.gz
  name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}'
  files:
  - LICENSE*
  - README*
  - deployment.yaml
dockers:
  - image: caarlos0/kube-shutdown-after
    tag_templates:
    - '{{ .Tag }}'
    - 'v{{ .Major }}.{{ .Minor }}'
    - 'latest'
