apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "kube-shutdown-after.fullname" . }}
  labels:
{{ include "kube-shutdown-after.labels" . | indent 4 }}
rules:
- apiGroups:
  - extensions
  - apps
  resources:
  - deployments
  verbs:
  - list
  - update
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "kube-shutdown-after.fullname" . }}
  labels:
{{ include "kube-shutdown-after.labels" . | indent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kube-shutdown-after
subjects:
- kind: {{ template "kube-shutdown-after.serviceAccountName" . }}
  name: kube-shutdown-after
  namespace: {{ .Release.Namespace }}
